name: Build CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: [8]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew clean build -xtest --stacktrace --no-daemon

  release:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    if: github.repository_owner == 'TCBuildMC' && github.event_name == 'push' && github.event.ref == 'refs/heads/stable' && contains(github.event.head_commit.message, '[publish]') == true
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      #      - name: get short sha
      #        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: read gradle.properties
        id: prop_info
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: "release_version"

      - name: create github release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ steps.prop_info.outputs.release_version }}"
          tag_name: "${{ steps.prop_info.outputs.release_version }}"
          target_commitish: ${{ github.event.ref }}
          generate_release_notes: true
          token: ${{ secrets.RELEASE_TOKEN }}
